### PR TITLE
addition of ExploreML section and other fixes

### PR DESCRIPTION
**Pull request by shyama7004**

### CODE REVIEW

**Comment by shyama7004** [comment]
Add the env.example

**Comment by Ayushi2234** [comment]
@shyama7004, why did you remove it then ?

**Comment by shyama7004** [comment]
I will add it. Sorry for inconvenience.

**Comment by Ayushi2234** [comment]
Looks fine but the highlighting feature isn't working as you mentioned. Please have a look once you're free .

**Comment by Ayushi2234** [comment]
@shyama7004 , can you fix the dark mode css of view-pdf section, looks weird.

**Pull request merged**
